[C++23] Add memory include to elf-file.h
Add memory include to elf-file.h to fix C++23 build errors because C++23
removed transitive includes.

Errors:
system/memory/libmeminfo/libelfutils/include/elfutils/elf-file.h:75:17:
error: no template named 'unique_ptr' in namespace 'std'
   75 |     static std::unique_ptr<ElfFile> create(const std::string&
path);
      |            ~~~~~^
system/memory/libmeminfo/libelfutils/include/elfutils/elf-file.h:79:17:
error: no template named 'unique_ptr' in namespace 'std'
   79 |     static std::unique_ptr<ElfFile> createFromIdent(const
std::string& path);
      |            ~~~~~^

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libelfutils
Change-Id: I57fc23e07176cbb12a24728c2fbe5b511903cd71